# Generated by Django 2.0.6 on 2018-06-08 03:25

from django.db import migrations
from django.core.management import call_command

def load_my_initial_data(apps, schema_editor):
    call_command("loaddata", "ios.json")
    call_command("loaddata", "io_types.json")


class Migration(migrations.Migration):

    dependencies = [
        ('manageTools', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_my_initial_data),
    ]
