# Generated by Django 2.0.6 on 2018-06-10 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manageTools', '0002_load_fixtures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usedio',
            name='pin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageTools.IO', verbose_name='Pin nr'),
        ),
    ]
