# Generated by Django 2.0.6 on 2018-06-10 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageTools', '0003_auto_20180610_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usedio',
            name='name',
            field=models.CharField(max_length=255, verbose_name='human readable name for the io'),
        ),
    ]
